apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Backend
    email: ee@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg

