apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: booking-api
  description: The Booking API
  tags:
    - javascript
    - typescript
    - graphql
    - nodejs
  links:
    - url: https://booking-api.test.cergea.com/graphql
      title: Booking API GraphQL
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  owner: guests
  lifecycle: production
  definition: graphql
