apiVersion: collinsonx/v1alpha1
kind: Component
metadata:
  name: backend-apps
  description: Mono-repo for all backend apis, such as booking, catalogue, consumer, entitlement, etc. 
  labels:
    collinsonx/type: api
  namespace: internal-systems
  tags:
    - javascript
    - typescript
    - nodejs
    - express
    - graphql
  links:
    - url: https://gateway-api.test.cergea.com/graphql
      title: Gateway API
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: backend-apps
  system: backend-apps
