apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-apps
  description: Monorepo for backend apis.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: james.knights@collinsonx.com
  lifecycle: production
