apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api
  description: Federated Graph for subgraphs.
  # Example for optional annotations
  annotations:
  #   github.com/project-slug: backstage/backstage
     backstage.io/techdocs-ref: dir:.
  tags:
    - javascript
    - typescript
    - graphql
    - nodejs
  links:
    - url: https://gateway-api.test.cergea.com/graphql
      title: Gateway API
      icon: dashboard
      type: admin-dashboard
spec:
  type: graphql
  owner: backend-apps
  lifecycle: production
  definition: graphql
  
