apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-apps
  description: Monorepo for backendapps
   annotations:
     github.com/project-slug: collinsonx/backend-apps
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: james.knights@collinsongroup.com
  lifecycle: production
