apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-apps
  description: Monorepo for backend apis.
  # Example for optional annotations
  annotations:
  #   github.com/project-slug: backstage/backstage
     backstage.io/techdocs-ref: dir:.
  tags:
    - javascript
    - typescript
    - graphql
    - nodejs
  links:
    - url: https://gateway-api.test.cergea.com/graphql
      title: Gateway API
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  owner: backend-apps
  system: backend-apps
  lifecycle: production
  providesApis:
    - booking-api
  
