apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-apps
  description: Mono-repo for all backend APIs, such as booking, catalogue, consumer, entitlement, etc.
   annotations:
     github.com/project-slug: collinsonx/backend-apps
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: james.knights@collinsongroup.com
  lifecycle: production
